In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
np.set_printoptions(precision=2)

# Concantenate numpy

In [13]:
x1 = np.random.rand(2, 5) * 10
x1

array([[1.11, 9.07, 7.09, 8.02, 2.4 ],
       [0.85, 3.84, 0.09, 9.45, 5.82]])

In [11]:
x2 = np.random.rand(2, 5) * -1
x2

array([[-0.44, -0.44, -0.92, -0.72, -0.55],
       [-0.55, -0.8 , -0.57, -0.57, -0.37]])

In [14]:
np.concatenate([x1, x2])

array([[ 1.11,  9.07,  7.09,  8.02,  2.4 ],
       [ 0.85,  3.84,  0.09,  9.45,  5.82],
       [-0.44, -0.44, -0.92, -0.72, -0.55],
       [-0.55, -0.8 , -0.57, -0.57, -0.37]])

In [15]:
np.concatenate([x1, x2]).shape

(4, 5)

In [16]:
np.concatenate([x1, x2], axis = 1)

array([[ 1.11,  9.07,  7.09,  8.02,  2.4 , -0.44, -0.44, -0.92, -0.72,
        -0.55],
       [ 0.85,  3.84,  0.09,  9.45,  5.82, -0.55, -0.8 , -0.57, -0.57,
        -0.37]])

In [17]:
np.concatenate([x1, x2], axis = 1).shape

(2, 10)

# Concatenate Pandas

In [18]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   1.11
b   9.07
c   7.09
d   8.02
e   2.40
dtype: float64

In [19]:
s2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   -0.44
d   -0.44
e   -0.92
f   -0.72
g   -0.55
dtype: float64

In [20]:
pd.concat([s1, s2])

a    1.11
b    9.07
c    7.09
d    8.02
e    2.40
c   -0.44
d   -0.44
e   -0.92
f   -0.72
g   -0.55
dtype: float64

In [21]:
pd.concat([s1, s2], axis=1)

0     1
a 1.11   NaN
b 9.07   NaN
c 7.09 -0.44
d 8.02 -0.44
e 2.40 -0.92
f  NaN -0.72
g  NaN -0.55

# Concatenate Dataframes

In [23]:
df1 = pd.DataFrame(np.random.rand(3, 2)*10, columns=['a', 'b'])
df1

a    b
0 7.43 5.26
1 2.77 5.77
2 9.80 7.74

In [24]:
df2 = pd.DataFrame(np.random.rand(3, 2)*-1, columns=['a', 'b'], index=[2, 3, 4])
df2

a     b
2 -0.28 -0.55
3 -0.49 -0.41
4 -0.96 -0.55

In [25]:
pd.concat([df1, df2])

a     b
0  7.43  5.26
1  2.77  5.77
2  9.80  7.74
2 -0.28 -0.55
3 -0.49 -0.41
4 -0.96 -0.55

In [26]:
pd.concat([df1, df2], axis=1)

a    b     a     b
0 7.43 5.26   NaN   NaN
1 2.77 5.77   NaN   NaN
2 9.80 7.74 -0.28 -0.55
3  NaN  NaN -0.49 -0.41
4  NaN  NaN -0.96 -0.55

In [27]:
pd.concat([df1, df2], axis=1, join='inner')

a    b     a     b
2 9.80 7.74 -0.28 -0.55

In [28]:
# Reset index

pd.concat([
    df1.reset_index(drop=True), 
    df2.reset_index(drop=True)
    ], axis=1)

a    b     a     b
0 7.43 5.26 -0.28 -0.55
1 2.77 5.77 -0.49 -0.41
2 9.80 7.74 -0.96 -0.55

In [29]:
df1.append(df2)

a     b
0  7.43  5.26
1  2.77  5.77
2  9.80  7.74
2 -0.28 -0.55
3 -0.49 -0.41
4 -0.96 -0.55

In [30]:
# Traspouse of dataframe

df1.T

0    1    2
a 7.43 2.77 9.80
b 5.26 5.77 7.74

In [31]:
# Append dataframes for columns

df1.T.append(df2.T).T

a    b     a     b
0 7.43 5.26   NaN   NaN
1 2.77 5.77   NaN   NaN
2 9.80 7.74 -0.28 -0.55
3  NaN  NaN -0.49 -0.41
4  NaN  NaN -0.96 -0.55